import 'package:flutter/material.dart';

const Color primaryColor = const Color(0xFF3FA5E4);
const Color primaryDarkColor = const Color(0xFF3396C);
const Color bgColor = const Color(0xFFFFFFFF);
const Color textPrimaryColor = const Color(0xFF161616);
const Color text444Color = const Color(0XFF444444);
const Color textSecondaryColor = const Color(0xFF3FA5E4);
const Color offWhiteColor = const Color(0xFFF9F9F9);
const Color greenColor = const Color(0XFF5CB85C);
const Color blackColor = const Color(0XFF000000);
const Color whiteColor = const Color(0XFFFFFFFF);
const Color darkGreyColor = const Color(0XFF808080);
const Color redColor = Colors.red;
const Color lightGreyColor = const Color(0XFF6B7280);
const Color dividerColor = Colors.grey;
const Color cloudBurst = const Color(0XFF374151);
const Color borderLineColor = const Color(0XFFD2D6DC);
const Color lightGreen = const Color(0XFF03543F);
const Color lightBgGreen = const Color(0XFFDEF7EC);
